# Generated by Django 5.2.5 on 2025-08-16 08:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("farmers", "0001_initial"),
        ("regions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(verbose_name="Price Date")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Price per Unit",
                    ),
                ),
                (
                    "quantity_available",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Quantity Available",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "submitted_via",
                    models.CharField(
                        choices=[
                            ("voice", "Voice Input"),
                            ("text", "Text Input"),
                            ("upload", "File Upload"),
                        ],
                        default="text",
                        max_length=10,
                        verbose_name="Submission Method",
                    ),
                ),
                (
                    "voice_transcript",
                    models.TextField(blank=True, verbose_name="Voice Transcript"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Additional Notes"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_prices",
                        to="farmers.farmer",
                        verbose_name="Farmer",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_prices",
                        to="regions.region",
                        verbose_name="Region",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_prices",
                        to="catalog.sku",
                        verbose_name="SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farmer Price",
                "verbose_name_plural": "Farmer Prices",
                "ordering": ["-date", "sku__name", "price"],
                "indexes": [
                    models.Index(
                        fields=["date", "sku", "region"],
                        name="pricing_far_date_279dc8_idx",
                    ),
                    models.Index(
                        fields=["farmer", "date"], name="pricing_far_farmer__38b78f_idx"
                    ),
                    models.Index(
                        fields=["sku", "region", "date"],
                        name="pricing_far_sku_id_b1a3b9_idx",
                    ),
                ],
                "unique_together": {("farmer", "sku", "date")},
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "min_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Minimum Price"
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Maximum Price"
                    ),
                ),
                (
                    "avg_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Average Price"
                    ),
                ),
                (
                    "median_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Median Price"
                    ),
                ),
                (
                    "total_submissions",
                    models.IntegerField(default=0, verbose_name="Total Submissions"),
                ),
                (
                    "total_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total Quantity Available",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="regions.region",
                        verbose_name="Region",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="catalog.sku",
                        verbose_name="SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price History",
                "verbose_name_plural": "Price Histories",
                "ordering": ["-date"],
                "unique_together": {("sku", "region", "date")},
            },
        ),
    ]
