# Generated by Django 4.2.23 on 2025-08-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farmer",
            options={
                "ordering": ["id"],
                "verbose_name": "Farmer",
                "verbose_name_plural": "Farmers",
            },
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="farmer_id",
        ),
    ]
