# Generated by Django 5.2.5 on 2025-08-16 08:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="SKU Code"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Product Name")),
                (
                    "name_ta",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Product Name (Tamil)"
                    ),
                ),
                (
                    "name_hi",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Product Name (Hindi)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fruit", "Fruit"),
                            ("vegetable", "Vegetable"),
                            ("grain", "Grain"),
                            ("spice", "Spice"),
                            ("other", "Other"),
                        ],
                        default="vegetable",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("gram", "Gram"),
                            ("quintal", "Quintal"),
                            ("ton", "Ton"),
                            ("piece", "Piece"),
                            ("dozen", "Dozen"),
                            ("bundle", "Bundle"),
                        ],
                        default="kg",
                        max_length=20,
                        verbose_name="Unit of Measurement",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sku_images/",
                        verbose_name="Product Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "min_order_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Minimum Order Quantity",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SKU",
                "verbose_name_plural": "SKUs",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="SKUImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(upload_to="sku_images/", verbose_name="Image"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Caption"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Is Primary Image"),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="catalog.sku",
                        verbose_name="SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "SKU Image",
                "verbose_name_plural": "SKU Images",
            },
        ),
    ]
