# Generated by Django 5.2.5 on 2025-08-16 08:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Email Notifications"
                    ),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(default=True, verbose_name="SMS Notifications"),
                ),
                (
                    "whatsapp_enabled",
                    models.BooleanField(
                        default=False, verbose_name="WhatsApp Notifications"
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Push Notifications"
                    ),
                ),
                (
                    "order_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Order Notifications"
                    ),
                ),
                (
                    "price_reminders",
                    models.BooleanField(
                        default=True, verbose_name="Price Submission Reminders"
                    ),
                ),
                (
                    "ranking_alerts",
                    models.BooleanField(default=True, verbose_name="Ranking Alerts"),
                ),
                (
                    "marketing_messages",
                    models.BooleanField(
                        default=False, verbose_name="Marketing Messages"
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("order_placed", "Order Placed"),
                            ("order_confirmed", "Order Confirmed"),
                            ("order_ready", "Order Ready"),
                            ("order_cancelled", "Order Cancelled"),
                            ("price_reminder", "Price Submission Reminder"),
                            ("payment_completed", "Payment Completed"),
                            ("farmer_verification", "Farmer Verification"),
                            ("low_ranking_alert", "Low Ranking Alert"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Template Name",
                    ),
                ),
                (
                    "subject_en",
                    models.CharField(max_length=200, verbose_name="Subject (English)"),
                ),
                (
                    "subject_ta",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Subject (Tamil)"
                    ),
                ),
                (
                    "subject_hi",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Subject (Hindi)"
                    ),
                ),
                ("message_en", models.TextField(verbose_name="Message (English)")),
                (
                    "message_ta",
                    models.TextField(blank=True, verbose_name="Message (Tamil)"),
                ),
                (
                    "message_hi",
                    models.TextField(blank=True, verbose_name="Message (Hindi)"),
                ),
                (
                    "sms_template_en",
                    models.TextField(blank=True, verbose_name="SMS Template (English)"),
                ),
                (
                    "sms_template_ta",
                    models.TextField(blank=True, verbose_name="SMS Template (Tamil)"),
                ),
                (
                    "sms_template_hi",
                    models.TextField(blank=True, verbose_name="SMS Template (Hindi)"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
            },
        ),
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("push", "Push Notification"),
                        ],
                        max_length=10,
                        verbose_name="Message Type",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Subject"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message Content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("read", "Read"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent At"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivered At"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read At"),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="External Message ID"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Additional Metadata"
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Log",
                "verbose_name_plural": "Message Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status"],
                        name="notificatio_recipie_45aa0d_idx",
                    ),
                    models.Index(
                        fields=["message_type", "status"],
                        name="notificatio_message_19286f_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_576450_idx"
                    ),
                ],
            },
        ),
    ]
